Implement Missions leaving and joining action
TesheMaximillan/Space-Travelere-s-Hub pull request #29
Opened 2022-05-11 16:13 UTC by TesheMaximillan

** Hi @Have-Samuel 

# In this milestone I did the following tasks

* Switch bades for missions - conditional components
* Implement mission leaving actions
* Implement mission joining actions
* organize project

2022-05-11 17:50 UTC, Have-Samuel requested changes
Excellent work done so far :1st_place_medal: but you need to make a few changes to the code, check out my comments below for more clarity.

And feel free to DM me in case of any issues

2022-05-11 17:50 UTC, Have-Samuel commented on src/App.js
> -import Myprofile from './components/Myprofile';
I think it's better to remove the unwanted code to make it clean and readable

2022-05-11 17:50 UTC, Have-Samuel commented on src/components/missions/Mission.jsx
> +    </tr>
I like the way you apply your styles in the reactjs files. :+1:

2022-05-11 17:50 UTC, Have-Samuel commented on src/components/missions/Status.jsx
> +        </td>
Nice use of the table element in your code. :100:

2022-05-11 18:43 UTC, TesheMaximillan commented on src/App.js
> -import Myprofile from './components/Myprofile';
👋 Hi, Have Samuel, 

# 
Thank you for your suggestion, however, to get a workable Navbar we need to add every router component, and Myprofile is one of the router components, so, when we add anything in each route we can easily navigate to each router components. Also, this is why we put it together in the first place

2022-05-12 15:02 UTC, Have-Samuel approved these changes
Excellent work done :100: Approved :+1: 
Nothing else is needed, go ahead and merge

2022-05-12 15:03 UTC, merged